[package]
name = "coreflux_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "coreflux_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
numpy = { version = "0.26.0" }
ndarray = "0.16.1"
ndarray-stats = "0.6.0"
